### ISSUE TITLE
HTTPS Certificate issue: MyCrypto, Inc [US] not seen

### ISSUE THREAD

**Issue by somotuk** [MyCryptoHQ/knowledge-base-content#152]
The documentation states to _**be sure that you see the green "MyCrypto, Inc [US]" bar in the URL bar**_ before downloading the desktop application.

While the certificate is marked as valid in the browser, the phrase "MyCrypto, Inc [US]" is not visible anywhere. If we look a the details of the certificate we see it has been issued by Amazon to mycrypto.com and that _the website does not supply ownership information._

We have the same issue with the other mycrypto sites: download.mycrypto.com, support.mycrypto.com etc.

**Comment by wtzb** [comment]
Hi there @somotuk! Thanks for noticing this. In the past, it would be possible to see "MyCrypto, Inc [US]" in your URL bar, but this has since removed by most major browsers, which is why you won't be seeing it anymore.  You can find more info about this change [here](https://www.troyhunt.com/extended-validation-certificates-are-really-really-dead/). I appreciate you noticing this, and we'll update it to reflect the current browser behavior. Thanks again!

**Comment by wtzb** [comment]
We have since updated the page. Thank you once again! We really appreciate you sharing it with us.
